# Generated by Django 2.1.2 on 2019-04-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190411_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryexam',
            name='agr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='art',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='bio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='bst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='chem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='comp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='cre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='english',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='kiswahili',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='maths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='music',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondaryexam',
            name='phy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
