# Generated by Django 2.1.2 on 2019-04-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20190411_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryexam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.School'),
        ),
    ]
