# Generated by Django 2.1.2 on 2019-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_universityexam_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
