# Generated by Django 2.1.2 on 2019-04-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_payment_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryexam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.School'),
        ),
    ]
