# Generated by Django 2.1.2 on 2019-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_secondaryexam_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryexam',
            name='klass',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
