# Generated by Django 2.1.2 on 2019-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_primaryexam_klass'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryexam',
            name='klass',
            field=models.CharField(blank=True, max_length=10, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='primaryexam',
            name='klass',
            field=models.CharField(blank=True, max_length=10, verbose_name='Class'),
        ),
    ]
